version: '3.7'
services:
  db:
    container_name: mongodb
    image: mongo:6
    restart: always
    environment:
      MONGODB_DATABASE: kimsasoft
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db